name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Android Emulator (faruktoptas)
        uses: faruktoptas/android-github-actions-emulator@1.1.0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter pub get
      - run: flutter test
      - run: flutter test integration_test
      - run: flutter build apk
                    
          
