name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Get dependencies
        run: flutter pub get


      - name: Run unit tests
        run: flutter test

      # - name: Run integration tests
        # run: flutter test integration_test

      - name: Build APK
        run: flutter build apk

